[[language]]
name = "css"
file-types = ["css"]
language-servers = ["tailwindcss-language-server"]
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "markdown"
file-types = ["md"]
language-servers = ["marksman"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true
soft-wrap.enable = true

[[language]]
name = "svelte"
language-servers = [
  "emmet-ls",
  "svelteserver",
  "typescript-language-server",
  "tailwindcss-lannguage-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier", args = ["--parser", "svelte"] }
auto-format = true

[[language]]
name = "typescript"
file-types = ["js", "ts"]
language-servers = [
  "eslint-language-server",
  "typescript-language-server",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
file-types = ["jsx", "tsx"]
language-servers = [
  "emmet-ls",
  "typescript-language-server",
  "tailwindcss-lannguage-server",
  "vscode-eslint-language-server",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true
soft-wrap.enable = true
